import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import './globals.css'
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" >
      <AuthProvider>
        <body className={inter.className}>
          <Navbar/>
          {children}
          <Toaster/>
        </body>
      </AuthProvider>
    </html>
  );
}